export const countries = [
  { label: "DZ", value: "Algeria" },
  { label: "AO", value: "Angola" },
  { label: "BJ", value: "Benin" },
  { label: "BW", value: "Botswana" },
  { label: "BF", value: "Burkina Faso" },
  { label: "BI", value: "Burundi" },
  { label: "CV", value: "Cabo Verde" },
  { label: "CM", value: "Cameroon" },
  { label: "CF", value: "Central African Republic (the)" },
  { label: "TD", value: "Chad" },
  { label: "KM", value: "Comoros (the)" },
  { label: "CD", value: "Congo (the Democratic Republic of the)" },
  { label: "CG", value: "Congo (the)" },
  { label: "CI", value: "Côte d'Ivoire" },
  { label: "DJ", value: "Djibouti" },
  { label: "EG", value: "Egypt" },
  { label: "GQ", value: "Equatorial Guinea" },
  { label: "ER", value: "Eritrea" },
  { label: "SZ", value: "Eswatini" },
  { label: "ET", value: "Ethiopia" },
  { label: "GA", value: "Gabon" },
  { label: "GM", value: "Gambia (the)" },
  { label: "GH", value: "Ghana" },
  { label: "GN", value: "Guinea" },
  { label: "GW", value: "Guinea-Bissau" },
  { label: "KE", value: "Kenya" },
  { label: "LS", value: "Lesotho" },
  { label: "LR", value: "Liberia" },
  { label: "LY", value: "Libya" },
  { label: "MG", value: "Madagascar" },
  { label: "MW", value: "Malawi" },
  { label: "ML", value: "Mali" },
  { label: "MR", value: "Mauritania" },
  { label: "MU", value: "Mauritius" },
  { label: "YT", value: "Mayotte" },
  { label: "MA", value: "Morocco" },
  { label: "MZ", value: "Mozambique" },
  { label: "NA", value: "Namibia" },
  { label: "NE", value: "Niger (the)" },
  { label: "NG", value: "Nigeria" },
  { label: "RE", value: "Réunion" },
  { label: "RW", value: "Rwanda" },
  { label: "SH", value: "Saint Helena, Ascension and Tristan da Cunha" },
  { label: "ST", value: "Sao Tome and Principe" },
  { label: "SN", value: "Senegal" },
  { label: "SC", value: "Seychelles" },
  { label: "SL", value: "Sierra Leone" },
  { label: "SO", value: "Somalia" },
  { label: "ZA", value: "South Africa" },
  { label: "SS", value: "South Sudan" },
  { label: "SD", value: "Sudan (the)" },
  { label: "TZ", value: "Tanzania, the United Republic of" },
  { label: "TG", value: "Togo" },
  { label: "TN", value: "Tunisia" },
  { label: "UG", value: "Uganda" },
  { label: "EH", value: "Western Sahara*" },
  { label: "ZM", value: "Zambia" },
  { label: "ZW", value: "Zimbabwe" },
  { label: "AQ", value: "Antarctica" },
  { label: "BV", value: "Bouvet Island" },
  { label: "TF", value: "French Southern Territories (the)" },
  { label: "HM", value: "Heard Island and McDonald Islands" },
  { label: "GS", value: "South Georgia and the South Sandwich Islands" },
  { label: "AF", value: "Afghanistan" },
  { label: "AM", value: "Armenia" },
  { label: "AZ", value: "Azerbaijan" },
  { label: "BD", value: "Bangladesh" },
  { label: "BT", value: "Bhutan" },
  { label: "IO", value: "British Indian Ocean Territory (the)" },
  { label: "BN", value: "Brunei Darussalam" },
  { label: "KH", value: "Cambodia" },
  { label: "CN", value: "China" },
  { label: "GE", value: "Georgia" },
  { label: "HK", value: "Hong Kong" },
  { label: "IN", value: "India" },
  { label: "ID", value: "Indonesia" },
  { label: "JP", value: "Japan" },
  { label: "KZ", value: "Kazakhstan" },
  { label: "KP", value: "Korea (the Democratic People's Republic of)" },
  { label: "KR", value: "Korea (the Republic of)" },
  { label: "KG", value: "Kyrgyzstan" },
  { label: "LA", value: "Lao People's Democratic Republic (the)" },
  { label: "MO", value: "Macao" },
  { label: "MY", value: "Malaysia" },
  { label: "MV", value: "Maldives" },
  { label: "MN", value: "Mongolia" },
  { label: "MM", value: "Myanmar" },
  { label: "NP", value: "Nepal" },
  { label: "PK", value: "Pakistan" },
  { label: "PH", value: "Philippines (the)" },
  { label: "SG", value: "Singapore" },
  { label: "LK", value: "Sri Lanka" },
  { label: "TW", value: "Taiwan (Province of China)" },
  { label: "TJ", value: "Tajikistan" },
  { label: "TH", value: "Thailand" },
  { label: "TL", value: "Timor-Leste" },
  { label: "TM", value: "Turkmenistan" },
  { label: "UZ", value: "Uzbekistan" },
  { label: "VN", value: "Viet Nam" },
  { label: "BZ", value: "Belize" },
];
